name: Data Manager

on:
  push:
    branches:
      - main
      - 1.4.x
  pull_request:
    branches:
      - main
      - 1.4.x
    paths-ignore:
      - "doc/**"

env:
  ENV_FILE: environment.yml
  PANDAS_CI: 1

jobs:
  data_manager:
    name: Test experimental data manager
    runs-on: ubuntu-latest
    timeout-minutes: 120
    services:
      moto:
        image: motoserver/moto
        env:
          AWS_ACCESS_KEY_ID: foobar_key
          AWS_SECRET_ACCESS_KEY: foobar_secret
        ports:
          - 5000:5000
    concurrency:
      # https://github.community/t/concurrecy-not-work-for-push/183068/7
      group: ${{ github.event_name == 'push' && github.run_number || github.ref }}-data_manager
      cancel-in-progress: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up pandas
      uses: ./.github/actions/setup

    - name: Run tests
      env:
        PANDAS_DATA_MANAGER: array
        PATTERN: "not network and not clipboard and not single_cpu"
        PYTEST_WORKERS: "auto"
        PYTEST_TARGET: pandas
      run: |
        source activate pandas-dev
        ci/run_tests.sh
